### ISSUE TITLE
wmake problem

### ISSUE THREAD

**Issue by filip21** [mortbauer/foamMeshToMED#2]
Hi, I'm not sure if someone is still reading this but here I go...
when trying to wmake the builder gets stuck at this error:
Make/linux64GccDPInt32Opt/foamToMED.o: In function `main':
foamToMED.C:(.text.startup+0xe75): undefined reference to`Foam::IOobjectList::IOobjectList(Foam::objectRegistry const&, Foam::fileName const&, Foam::fileName const&)'
collect2: error: ld returned 1 exit status

I'm building with OF 3.0.1 and Ubuntu 15.10.
I tried linking all linkable libraries in the /opt/openfoam30 directory but to no real advantage.
Thank you for any help,
Kind regards
Filip

**Comment by mortbauer** [comment]
hm, well i developed it for OF 2.3, maybe it needs some adaption for the new version, however from the error message i have the impression that it doesn't find the OF library at all. Maybe you could add '-lOpenFoam' to the options file in the Make directory.

**Comment by filip21** [comment]
hm, I tried using the '-lOpenFOAM' option before but the issue seemed to be still present (along with other small problems I was able to solve.
However once i switched to OF2.3, added the position of hdf5.h and med.h everything went smoothly.
Thank you for the great tool, it seems to work really well
Filip

**Comment by mortbauer** [comment]
Im happy it is usefull to you!
